## code generation
# FLASHSTART=0x0
RAMSTART=0x20080000
# WATCHDOG=1
RAMSIZE=32K
DEFINE="ETRSIZE=0x1000"

target: target-a5

include ${T32SYS}/demo/arm/compiler/gnu-make/cortex-a/makefile

-include special-rule.mk.internal

