## code generation
FLASHSTART=0x0
RAMSTART=0x20000000
WATCHDOG=1
RAMSIZE=0x3800
DEFINE=RAM_ECC_LONG

include ${T32SYS}/demo/arm/compiler/gnu-make/cortex-m/makefile

target: target-m0p
	

# include special-rule.mk.internal if existing - for Lauterbach internal usage
-include special-rule.mk.internal

