## code generation
FLASHSTART=0x11000000
RAMSTART=0x18000000
TARGET=midi.c
# WATCHDOG=1

include ${T32SYS}/demo/arm/compiler/gnu-make/cortex-m/makefile

target: target-m3
	

# include special-rule.mk.internal if existing - for Lauterbach internal usage
-include special-rule.mk.internal

