## code generation
# FLASHSTART=0x0
RAMSTART=0x99100000
TARGET=sieve.c stm_stimulus.c
# WATCHDOG=1

include ${T32SYS}/demo/arm/compiler/gnu-make/cortex-m/makefile

target: target-m7
	

# include special-rule.mk.internal if existing - for Lauterbach internal usage
-include special-rule.mk.internal

