## code generation
# FLASHSTART=0x0
RAMSTART=0xffff0100
# WATCHDOG=1
RAMSIZE=0x8000
DEFINE=ETRSIZE=0x4000

include ${T32SYS}/demo/arm/compiler/gnu-make/cortex-r/makefile

target: target-r5


# include special-rule.mk.internal if existing - for Lauterbach internal usage
-include special-rule.mk.internal

