## code generation
# FLASHSTART=0x0
RAMSTART=0x0
# WATCHDOG=1
# RAMSIZE=0x8000
# DEFINE=ETRSIZE=0x1000
HARDFP=1

include ${T32SYS}/demo/arm/compiler/gnu-make/cortex-m/makefile

target: target-m4
	

# include special-rule.mk.internal if existing - for Lauterbach internal usage
-include special-rule.mk.internal

