## code generation
FLASHSTART=0xA00000
RAMSTART=0x0
WATCHDOG=1
DEFINE=RAMSIZE=0x4000 RAMSTART=${RAMSTART} RAM_ECC_LONG

include ${T32SYS}/demo/arm/compiler/gnu-make/cortex-r/makefile

-include special-rule.mk.internal

