## code generation
FLASHSTART=0xA00000
RAMSTART=0x0
WATCHDOG=1
RAMSIZE=0x4000
DEFINE=RAM_ECC_LONG

include ${T32SYS}/demo/arm/compiler/gnu-make/cortex-r/makefile

target: target-r5
	

-include special-rule.mk.internal

