## code generation
# FLASHSTART=0x0
RAMSTART=0x2F000000
# WATCHDOG=1
RAMSIZE=0x8000
DEFINE=ETRSIZE=0x1000

include ${T32SYS}/demo/arm/compiler/gnu-make/cortex-a/makefile

target: target-a7
	

# include special-rule.mk.internal if existing - for Lauterbach internal usage
-include special-rule.mk.internal

