## code generation
# FLASHSTART=0x0
RAMSTART=0x00900000
# WATCHDOG=1
HARDFP=VFPv4
RAMSIZE=0x20000
DEFINE=ETRSIZE=0x10000

include ${T32SYS}/demo/arm/compiler/gnu-make/cortex-a/makefile

target: target-a7
	

# include special-rule.mk.internal if existing - for Lauterbach internal usage
-include special-rule.mk.internal

