## code generation
# FLASHSTART=0x0
RAMSTART=0x3f000000
# WATCHDOG=1
HARDFP=VFPv3

include ${T32SYS}/demo/arm/compiler/gnu-make/cortex-a/makefile

target: target-a5
	

# include special-rule.mk.internal if existing - for Lauterbach internal usage
-include special-rule.mk.internal

