## code generation
FLASHSTART=0x00200000
RAMSTART=0x000B0000
# WATCHDOG=1

include ${T32SYS}/demo/arm/compiler/gnu-make/cortex-m/makefile

target: target-m4
	

# include special-rule.mk.internal if existing - for Lauterbach internal usage
-include special-rule.mk.internal

