## code generation
# FLASHSTART=0x0
RAMSTART=0x0
# WATCHDOG=1
RAMSIZE=0xffff

include ${T32SYS}/demo/arm/compiler/gnu-make/cortex-r/makefile

target: target-r5
	

# include special-rule.mk.internal if existing - for Lauterbach internal usage
-include special-rule.mk.internal

